/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#335083",
        "surface-container": "#edeeef",
        "surface": "#f8f9fa",
        "on-secondary-fixed": "#001b3f",
        "on-background": "#191c1d",
        "on-tertiary-container": "#6bb73a",
        "outline-variant": "#c4c6d0",
        "primary-container": "#1a3a6b",
        "secondary": "#415e91",
        "primary": "#002451",
        "inverse-surface": "#2e3132",
        "on-primary-fixed": "#001b3f",
        "on-tertiary-fixed-variant": "#225100",
        "primary-fixed-dim": "#abc7ff",
        "surface-container-lowest": "#ffffff",
        "background": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "surface-tint": "#415e91",
        "inverse-primary": "#abc7ff",
        "surface-dim": "#d9dadb",
        "surface-variant": "#e1e3e4",
        "on-primary-fixed-variant": "#284678",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#a7f873",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#43474f",
        "secondary-fixed": "#d7e2ff",
        "on-primary": "#ffffff",
        "tertiary-container": "#1b4300",
        "tertiary": "#0f2b00",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#abc7ff",
        "secondary-container": "#a7c4fe",
        "tertiary-fixed-dim": "#8cda5a",
        "surface-container-high": "#e7e8e9",
        "on-surface": "#191c1d",
        "on-secondary-fixed-variant": "#284678",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9fa",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#0a2100",
        "surface-container-low": "#f3f4f5",
        "on-primary-container": "#89a5dd",
        "primary-fixed": "#d7e2ff",
        "outline": "#747780",
        "on-error-container": "#93000a",
        // Keep old colors as aliases for mobile pages that still use them
        success: '#16A34A',
        star: '#EAB308',
        muted: '#64748B',
        disabled: '#CBD5E1',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
